In [1]:
import tensorflow as tf 
print(tf.__version__)

2.8.2


In [2]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
scalar.ndim

0

In [5]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
vector.ndim

1

In [8]:
matrix = tf.constant([[10,7],
                       [3,20]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3, 20]], dtype=int32)>

In [9]:
another_matrix = tf.constant([[10,7],
                             [3,2],
                             [5,6]],dtype = tf.int32)

another_matrix

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  2],
       [ 5,  6]], dtype=int32)>

In [10]:
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[10,20,30],
                       [40,0,87]],
                      [[12,25,68],
                       [45,85,61]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 20, 30],
        [40,  0, 87]],

       [[12, 25, 68],
        [45, 85, 61]]], dtype=int32)>

In [11]:
tensor.ndim

3

In [12]:
tensor.shape

TensorShape([3, 2, 3])

In [13]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,4])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  4], dtype=int32)>)

In [14]:
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [15]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [16]:
unchangeable_tensor[0].assign(3)
unchangeable_tensor

AttributeError: ignored

In [21]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_1,random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [24]:
random_3 = tf.random.Generator.from_seed(42)
random_3 = random_3.normal(shape=(3,2))
random_4 = tf.random.Generator.from_seed(11)
random_4 = random_4.normal(shape=(3,4))
random_3, random_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[ 0.27305737, -0.29925638, -0.3652325 ,  0.61883307],
        [-1.0130816 ,  0.28291714,  1.2132233 ,  0.46988967],
        [ 0.37944323, -0.6664026 ,  0.6054596 ,  0.19181173]],
       dtype=float32)>)

In [25]:
not_shuffled = tf.constant([[10,7],
                            [14,23],
                            [74,58]])

tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[74, 58],
       [10,  7],
       [14, 23]], dtype=int32)>

In [26]:
tf.random.shuffle(not_shuffled,seed=45)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [74, 58],
       [14, 23]], dtype=int32)>

In [27]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [14, 23],
       [74, 58]], dtype=int32)>

In [28]:
tf.random.set_seed(42)

tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[14, 23],
       [74, 58],
       [10,  7]], dtype=int32)>

In [29]:
tf.ones(shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [30]:
tf.zeros(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [33]:
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [35]:
A = tf.constant(numpy_A,shape=(2,4,3))
A

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]], dtype=int32)>

In [36]:
rank_4_tensor = tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [37]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [38]:
print("Datatypr of Every Element",rank_4_tensor.shape)
print("Number of dimensions (rank):",rank_4_tensor.ndim)
print("Shape of tensor:",rank_4_tensor.shape)
print("elements along axis 0 of tensor", rank_4_tensor.shape[0])
print("Elements along last axis of tensor", rank_4_tensor.shape[-1])
print("Total number of elements",tf.size(rank_4_tensor).numpy())

Datatypr of Every Element (2, 3, 4, 5)
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
elements along axis 0 of tensor 2
Elements along last axis of tensor 5
Total number of elements 120


In [40]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [41]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [43]:
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [45]:
rank_2_tensor = tf.constant([[10,7],
                             [3,4]])

rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [48]:
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [49]:
tf.expand_dims(rank_2_tensor,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [50]:
tensor = tf.constant([[10,5],
                      [20,13]])

tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 15],
       [30, 23]], dtype=int32)>

In [51]:
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  50],
       [200, 130]], dtype=int32)>

In [52]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 115],
       [460, 269]], dtype=int32)>

In [53]:
X = tf.constant([[14,45],
                 [78,53],
                 [74,21]])

Y = tf.constant([[42,65],
                 [48,52],
                 [63,47]])

X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[14, 45],
        [78, 53],
        [74, 21]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[42, 65],
        [48, 52],
        [63, 47]], dtype=int32)>)

In [55]:
tf.reshape(Y,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[42, 65, 48],
       [52, 63, 47]], dtype=int32)>

In [57]:
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[2928, 3745, 2787],
       [6032, 8409, 6235],
       [4200, 6133, 4539]], dtype=int32)>

In [58]:
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[3513, 3012, 2997],
       [6721, 6500, 7405],
       [4473, 4644, 5649]], dtype=int32)>

In [59]:
B = tf.constant([1.7,7.4])
B , tf.cast(B,dtype=tf.int32)

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>)

In [61]:
B = B-10
B,tf.abs(B)

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-8.3, -2.6], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([8.3, 2.6], dtype=float32)>)

In [ ]:
E = tf.constant(np.random.randint(low=0,high=100,size=50))